name: Publish

on:
  push:
    branches:
      - master

jobs:
  publish:
    if: "contains(github.event.head_commit.message, 'chore(release)')"

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2

    - uses: actions/setup-node@v2
      with:
        node-version: '14.x'
  
    - name: Install
      run: |
        npm i -g lerna@^3.22.1
        npm run bootstrap

    - name: Publish
      run: npm publish --dry-run
      # run: npm run publish:beta
      env:
        NODE_AUTH_TOKEN: ${{ secrets.SUPER_OLEG_NPM_AUTH_TOKEN }}
